server:
  port: 8080

services:
  auth:
    url: http://localhost:8081
  catalog:
    url: http://localhost:8082
  sales:
    url: http://localhost:8083
  billing:
    url: http://localhost:8084
  inventory:
    url: http://localhost:8087
  operations:
    url: http://localhost:8086
  accounting:
    url: http://localhost:8088
  payments:
    url: http://localhost:8089
  purchases:
    url: http://localhost:8090
  payroll:
    url: http://localhost:8091
  marketing:
    url: http://localhost:8092

logging:
  level:
    com.poscl.bff: DEBUG
    org.springframework.web: INFO
