[build]
builder = "dockerfile"
dockerfilePath = "marketing-service/Dockerfile"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 600
startCommand = "java -Xmx256m -jar app.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
